---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: kubernetes-controller
    app.kubernetes.io/instance: hashring-controller
    app.kubernetes.io/name: hashring-controller
  name: hashring-controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: kubernetes-controller
    app.kubernetes.io/instance: hashring-controller
    app.kubernetes.io/name: hashring-controller
    app.kubernetes.io/version: main
  name: hashring-controller
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - watch
      - get
      - create
      - update
      - delete
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices
    verbs:
      - list
      - watch
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: kubernetes-controller
    app.kubernetes.io/instance: hashring-controller
    app.kubernetes.io/name: hashring-controller
    app.kubernetes.io/version: main
  name: hashring-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hashring-controller
subjects:
  - kind: ServiceAccount
    name: hashring-controller

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hashring-controller
  labels:
    app: hashring-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashring-controller
  template:
    metadata:
      labels:
        app: hashring-controller
    spec:
      serviceAccountName: hashring-controller
      containers:
        - name: hashring-controller
          image: quay.io/philipgough/hashring-controller:latest
          args: ["--namespace=$(NAMESPACE)"]
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 30
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
